spring:
  application:
    name: cloud-storage

  datasource:
    url: jdbc:postgresql://192.168.0.125:3434/postgres
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: cloudStorage

  data:
    redis:
      host: 192.168.0.125
      port: 6379

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  profiles:
    active: restControllerSecurity
#    active: filterSecurity


minio:
  bucket-name: user-files
  endpoint: http://192.168.0.125:9000
  user: user
  password: 12345678


#  session:
#    redis:
#      repository-type: indexed



#security:
#  type: restControllerSecurity