spring:
  application:
    name: cloud-storage

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: cloudStorage

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  profiles:
    active: restControllerSecurity
#    active: filterSecurity


minio:
  bucket-name: user-files
  endpoint: ${MINIO_URL}
  user: ${MINIO_ROOT_USER}
  password: ${MINIO_ROOT_PASSWORD}


#  session:
#    redis:
#      repository-type: indexed



#security:
#  type: restControllerSecurity